// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBucoQaRBe6OKIzmXtBLqokAplu9OGR18U',
    appId: '1:674156355483:web:0fe199817f1ca461e94b3e',
    messagingSenderId: '674156355483',
    projectId: 'tailortech-8a377',
    authDomain: 'tailortech-8a377.firebaseapp.com',
    storageBucket: 'tailortech-8a377.firebasestorage.app',
    measurementId: 'G-DY3MXWVZW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJX1KS575laIPjyl3tuPvJNxPofNNXryE',
    appId: '1:674156355483:android:eeacc3993697ecb9e94b3e',
    messagingSenderId: '674156355483',
    projectId: 'tailortech-8a377',
    storageBucket: 'tailortech-8a377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfuVAMyEc4eNyS47aZmT3WFEIOz751U8k',
    appId: '1:674156355483:ios:2b63a090670648f5e94b3e',
    messagingSenderId: '674156355483',
    projectId: 'tailortech-8a377',
    storageBucket: 'tailortech-8a377.firebasestorage.app',
    iosBundleId: 'com.example.dashboardNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfuVAMyEc4eNyS47aZmT3WFEIOz751U8k',
    appId: '1:674156355483:ios:2b63a090670648f5e94b3e',
    messagingSenderId: '674156355483',
    projectId: 'tailortech-8a377',
    storageBucket: 'tailortech-8a377.firebasestorage.app',
    iosBundleId: 'com.example.dashboardNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBucoQaRBe6OKIzmXtBLqokAplu9OGR18U',
    appId: '1:674156355483:web:65e3ee75eda4204ae94b3e',
    messagingSenderId: '674156355483',
    projectId: 'tailortech-8a377',
    authDomain: 'tailortech-8a377.firebaseapp.com',
    storageBucket: 'tailortech-8a377.firebasestorage.app',
    measurementId: 'G-9W8SYTKJ4N',
  );
}
